#!/usr/bin/env bash
# Bootstrap multiplataforma de setup-skills. Genera las instrucciones locales
# y ejecuta los provisionadores disponibles. Seguro al repetirse (idempotente).
set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DST="$HOME/.claude/skills"
SETTINGS="$HOME/.claude/settings.json"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CODEX_SKILLS_DST="$CODEX_HOME/skills"
VERSIONS="$BASE/tool-versions.env"
PLATFORM_REGISTRY="$BASE/platforms.txt"
INSTRUCTIONS_SOURCE="$BASE/PROJECT_INSTRUCTIONS.md"
GENERATED_MARKER='<!-- Generated by setup-skills from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->'
SELECTED_PLATFORMS=""
INSTRUCTIONS_ONLY=0

usage() {
  cat >&2 <<EOF
Uso: $0 [--platform <nombre>]... [--instructions-only]

Sin --platform, detecta todos los CLI registrados disponibles en PATH.
EOF
}

add_platform() {
  local platform="$1"
  if printf '%s\n' "$SELECTED_PLATFORMS" | grep -Fx "$platform" >/dev/null 2>&1; then
    return
  fi
  if [ -n "$SELECTED_PLATFORMS" ]; then
    SELECTED_PLATFORMS="$SELECTED_PLATFORMS
$platform"
  else
    SELECTED_PLATFORMS="$platform"
  fi
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --platform)
      [ "$#" -ge 2 ] || { usage; exit 2; }
      add_platform "$2"
      shift 2
      ;;
    --instructions-only)
      INSTRUCTIONS_ONLY=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

if [ ! -f "$PLATFORM_REGISTRY" ] || [ ! -f "$INSTRUCTIONS_SOURCE" ]; then
  echo "ERROR: faltan platforms.txt o PROJECT_INSTRUCTIONS.md" >&2
  exit 1
fi

if [ -z "$SELECTED_PLATFORMS" ]; then
  SELECTED_PLATFORMS="$(
    while IFS='|' read -r platform cli_command version_argument instructions_file detail; do
      [ -n "$platform" ] || continue
      [ "${platform#\#}" = "$platform" ] || continue
      if command -v "$cli_command" >/dev/null 2>&1; then
        printf '%s\n' "$platform"
      fi
    done < "$PLATFORM_REGISTRY"
  )"
fi

if [ -z "$SELECTED_PLATFORMS" ]; then
  echo "ERROR: no se detecto ningun CLI registrado; usa --platform <nombre>" >&2
  exit 1
fi

generate_instruction_file() {
  local platform="$1"
  local instructions_file destination temporary first_line

  instructions_file="$(awk -F'|' -v wanted="$platform" '
    $1 !~ /^#/ && $1 == wanted { print $4; found = 1; exit }
    END { if (!found) exit 1 }
  ' "$PLATFORM_REGISTRY")" || {
    echo "ERROR: plataforma no registrada: $platform" >&2
    return 1
  }

  case "$instructions_file" in
    ''|*/*|*[!A-Za-z0-9._-]*)
      echo "ERROR: archivo de instrucciones invalido para $platform: $instructions_file" >&2
      return 1
      ;;
  esac

  destination="$BASE/$instructions_file"
  if [ -L "$destination" ]; then
    echo "ERROR: $destination es un symlink; no se reemplaza" >&2
    return 1
  fi
  if [ -e "$destination" ]; then
    if [ ! -f "$destination" ]; then
      echo "ERROR: $destination existe y no es un archivo regular" >&2
      return 1
    fi
    first_line="$(sed -n '1p' "$destination")"
    if [ "$first_line" != "$GENERATED_MARKER" ]; then
      echo "ERROR: $destination no es administrado por setup-skills; se conserva" >&2
      return 1
    fi
  fi

  temporary="$(mktemp "$BASE/.instructions.XXXXXX")"
  {
    printf '%s\n\n' "$GENERATED_MARKER"
    cat "$INSTRUCTIONS_SOURCE"
  } > "$temporary"

  if [ -f "$destination" ] && cmp -s "$temporary" "$destination"; then
    rm -f "$temporary"
    echo "OK  $instructions_file ya esta actualizado para $platform"
    return
  fi

  mv "$temporary" "$destination"
  echo "OK  $instructions_file generado para $platform"
}

printf '%s\n' "$SELECTED_PLATFORMS" | while IFS= read -r platform; do
  [ -n "$platform" ] || continue
  generate_instruction_file "$platform"
done

if [ "$INSTRUCTIONS_ONLY" -eq 1 ]; then
  echo "==> Archivos de instrucciones listos"
  exit 0
fi

if [ ! -x "$BASE/verify-compatibility.sh" ]; then
  echo "ERROR: falta el verificador ejecutable $BASE/verify-compatibility.sh" >&2
  exit 1
fi

verify_selected_platforms() {
  local phase="$1"
  local result output
  printf '%s\n' "$SELECTED_PLATFORMS" | while IFS= read -r platform; do
    [ -n "$platform" ] || continue
    if [ "$phase" = "pre" ]; then
      if output="$("$BASE/verify-compatibility.sh" --platform "$platform" --phase "$phase" 2>&1)"; then
        continue
      else
        result=$?
      fi
      if [ "$result" -eq 2 ]; then
        continue
      fi
      printf '%s\n' "$output" >&2
      return "$result"
    fi

    if "$BASE/verify-compatibility.sh" --platform "$platform" --phase "$phase"; then
      continue
    else
      result=$?
    fi
    if [ "$result" -eq 2 ]; then
      echo "AVISO: $platform requiere adaptadores; se continuara con lo disponible" >&2
    else
      return "$result"
    fi
  done
}

platform_is_selected() {
  printf '%s\n' "$SELECTED_PLATFORMS" | grep -Fx "$1" >/dev/null 2>&1
}

if platform_is_selected claude || platform_is_selected codex; then
  if [ ! -f "$VERSIONS" ]; then
    echo "ERROR: no se encontro $VERSIONS" >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  . "$VERSIONS"
  : "${CLAUDE_MEM_VERSION:?Falta CLAUDE_MEM_VERSION en tool-versions.env}"
fi

verify_selected_platforms pre

echo "==> Usando setup-skills en: $BASE"

normalize_git_url() {
  local value="${1%/}"
  printf '%s\n' "${value%.git}"
}

validate_repo_source() {
  local name="$1"
  local dest="$2"
  local required

  case "$name" in
    superpowers) required="skills/using-superpowers/SKILL.md" ;;
    prompt-master) required="SKILL.md" ;;
    abogado-del-diablo) required="skills/abogado-del-diablo/SKILL.md" ;;
    the-architect) required="CLAUDE.md" ;;
    context7) required="packages/mcp/package.json" ;;
    claude-token-efficient) required="CLAUDE.md" ;;
    *) required="README.md" ;;
  esac

  if [ ! -f "$dest/$required" ]; then
    echo "ERROR: $name no contiene el archivo esperado: $required" >&2
    return 1
  fi
}

ensure_clean_tracked_state() {
  local name="$1"
  local dest="$2"
  if ! git -C "$dest" diff --quiet || ! git -C "$dest" diff --cached --quiet; then
    echo "ERROR: $name tiene cambios rastreados; guardalos antes de reconciliar la version" >&2
    return 1
  fi
}

reconcile_repo() {
  local name="$1"
  local url="$2"
  local branch="$3"
  local commit="$4"
  local mode="$5"
  local dest="$BASE/$name"
  local current_url current_commit desired_commit

  case "$mode" in
    pinned)
      if [ -z "$commit" ] || [ "$commit" = "-" ]; then
        echo "ERROR: $name esta en modo pinned pero no declara commit" >&2
        return 1
      fi
      ;;
    shallow) ;;
    *)
      echo "ERROR: modo desconocido para $name: $mode" >&2
      return 1
      ;;
  esac

  if [ -e "$dest" ] && [ ! -d "$dest/.git" ]; then
    echo "ERROR: $dest existe pero no es un repositorio Git administrable" >&2
    return 1
  fi

  if [ ! -d "$dest/.git" ]; then
    if [ "$mode" = "shallow" ]; then
      echo "==> clone shallow $name ($branch)"
      git clone --depth 1 --branch "$branch" "$url" "$dest"
    else
      echo "==> clone $name (pinned $commit)"
      git clone "$url" "$dest"
      git -C "$dest" checkout --detach "$commit"
    fi
    validate_repo_source "$name" "$dest"
    return
  fi

  current_url="$(git -C "$dest" config --get remote.origin.url || true)"
  if [ -z "$current_url" ] || [ "$(normalize_git_url "$current_url")" != "$(normalize_git_url "$url")" ]; then
    echo "ERROR: $name existe pero su origin no coincide" >&2
    echo "  Actual:   ${current_url:-(sin origin)}" >&2
    echo "  Esperado: $url" >&2
    return 1
  fi

  current_commit="$(git -C "$dest" rev-parse HEAD)"
  if [ "$mode" = "pinned" ]; then
    desired_commit="$commit"
    if [ "$current_commit" = "$desired_commit" ]; then
      echo "OK  $name coincide con el commit fijado ($desired_commit)"
      validate_repo_source "$name" "$dest"
      return
    fi

    ensure_clean_tracked_state "$name" "$dest"
    if ! git -C "$dest" cat-file -e "$desired_commit^{commit}" 2>/dev/null; then
      git -C "$dest" fetch origin "$desired_commit"
    fi
  else
    git -C "$dest" fetch origin "$branch"
    desired_commit="$(git -C "$dest" rev-parse FETCH_HEAD)"
    if [ "$current_commit" = "$desired_commit" ]; then
      echo "OK  $name ya coincide con el ultimo commit de $branch ($desired_commit)"
      validate_repo_source "$name" "$dest"
      return
    fi
    ensure_clean_tracked_state "$name" "$dest"
  fi

  echo "==> Reconciliando $name: $current_commit -> $desired_commit"
  git -C "$dest" checkout --detach "$desired_commit"
  validate_repo_source "$name" "$dest"
}

resolve_symlink_dir() {
  local link="$1"
  local raw candidate
  raw="$(readlink "$link")"
  case "$raw" in
    /*) candidate="$raw" ;;
    *) candidate="$(dirname "$link")/$raw" ;;
  esac
  (cd "$candidate" 2>/dev/null && pwd -P)
}

# --- 0. Clonar repos de terceros desde el manifiesto -------------------
# Solo referencias: el repo propio no versiona el codigo de terceros, lo
# clona aqui. Lee third-party-repos.txt (nombre|url|branch|commit|modo).
MANIFEST="$BASE/third-party-repos.txt"
if [ -f "$MANIFEST" ]; then
  echo "==> Validando repos de terceros (manifiesto: third-party-repos.txt)"
  while IFS='|' read -r name url branch commit mode; do
    case "$name" in
      ''|\#*) continue ;;  # ignora lineas vacias y comentarios
    esac
    reconcile_repo "$name" "$url" "$branch" "$commit" "$mode"
  done < "$MANIFEST"
else
  echo "ERROR: no se encontro $MANIFEST" >&2
  exit 1
fi

verify_selected_platforms post

# --- 1. Provisionador actual de Claude: symlinks de skills -------------
if platform_is_selected claude; then
mkdir -p "$SKILLS_DST"

# macOS trae bash 3.2 (sin arrays asociativos), por eso usamos pares "name|target".
SKILL_LINKS="
commit-style|$BASE/skills/commit-style
prompt-master|$BASE/prompt-master
abogado-del-diablo|$BASE/abogado-del-diablo/skills/abogado-del-diablo
brainstorming|$BASE/superpowers/skills/brainstorming
dispatching-parallel-agents|$BASE/superpowers/skills/dispatching-parallel-agents
executing-plans|$BASE/superpowers/skills/executing-plans
finishing-a-development-branch|$BASE/superpowers/skills/finishing-a-development-branch
receiving-code-review|$BASE/superpowers/skills/receiving-code-review
requesting-code-review|$BASE/superpowers/skills/requesting-code-review
subagent-driven-development|$BASE/superpowers/skills/subagent-driven-development
systematic-debugging|$BASE/superpowers/skills/systematic-debugging
test-driven-development|$BASE/superpowers/skills/test-driven-development
using-git-worktrees|$BASE/superpowers/skills/using-git-worktrees
using-superpowers|$BASE/superpowers/skills/using-superpowers
verification-before-completion|$BASE/superpowers/skills/verification-before-completion
writing-plans|$BASE/superpowers/skills/writing-plans
writing-skills|$BASE/superpowers/skills/writing-skills
"

echo "$SKILL_LINKS" | while IFS='|' read -r name target; do
  [ -z "$name" ] && continue
  link="$SKILLS_DST/$name"
  if [ ! -d "$target" ]; then
    echo "AVISO: falta $target (submodulo/repo no clonado?) - se omite $name"
    continue
  fi

  target_resolved="$(cd "$target" && pwd -P)"
  if [ -L "$link" ]; then
    link_resolved="$(resolve_symlink_dir "$link" || true)"
    if [ "$link_resolved" = "$target_resolved" ]; then
      echo "OK  $name ya apunta al destino administrado"
      continue
    fi
    echo "ERROR: $link es un symlink administrado por otra fuente" >&2
    echo "  Actual:   $(readlink "$link")" >&2
    echo "  Esperado: $target" >&2
    exit 1
  elif [ -e "$link" ]; then
    echo "ERROR: $link existe y no es un symlink; no se reemplaza" >&2
    exit 1
  fi

  ln -s "$target" "$link"
  echo "OK  $name -> $target"
done

# --- 2. Superpowers: CLAUDE_PLUGIN_ROOT y hook SessionStart -------------
echo "==> Actualizando settings.json (CLAUDE_PLUGIN_ROOT + hook de superpowers)"
python3 - "$SETTINGS" "$BASE/superpowers" <<'PYEOF'
import json
import os
import stat
import sys
import tempfile

settings_path, superpowers_root = sys.argv[1], sys.argv[2]

if os.path.exists(settings_path):
    with open(settings_path, encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {}

if not isinstance(data, dict):
    raise SystemExit("settings.json debe contener un objeto JSON")

env = data.setdefault("env", {})
if not isinstance(env, dict):
    raise SystemExit("settings.json: 'env' debe ser un objeto")
env["CLAUDE_PLUGIN_ROOT"] = superpowers_root

hooks = data.setdefault("hooks", {})
if not isinstance(hooks, dict):
    raise SystemExit("settings.json: 'hooks' debe ser un objeto")

session_start = hooks.setdefault("SessionStart", [])
if not isinstance(session_start, list):
    raise SystemExit("settings.json: 'hooks.SessionStart' debe ser una lista")

hook_cmd = f"{superpowers_root}/hooks/run-hook.cmd session-start"
managed_hook = None
target_group = None
for index, group in enumerate(session_start):
    if not isinstance(group, dict):
        raise SystemExit(f"settings.json: SessionStart[{index}] debe ser un objeto")
    group_hooks = group.get("hooks")
    if group_hooks is None:
        continue
    if not isinstance(group_hooks, list):
        raise SystemExit(f"settings.json: SessionStart[{index}].hooks debe ser una lista")
    if target_group is None:
        target_group = group
    for hook_index, item in enumerate(group_hooks):
        if not isinstance(item, dict):
            raise SystemExit(
                f"settings.json: SessionStart[{index}].hooks[{hook_index}] debe ser un objeto"
            )
        if (
            item.get("type") == "command"
            and "run-hook.cmd session-start" in item.get("command", "")
        ):
            managed_hook = item

if managed_hook is not None:
    managed_hook["command"] = hook_cmd
else:
    if target_group is None:
        target_group = {"hooks": []}
        session_start.append(target_group)
    target_group["hooks"].append({"type": "command", "command": hook_cmd})

settings_dir = os.path.dirname(settings_path)
os.makedirs(settings_dir, exist_ok=True)
fd, temp_path = tempfile.mkstemp(prefix=".settings.", suffix=".json", dir=settings_dir)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    if os.path.exists(settings_path):
        os.chmod(temp_path, stat.S_IMODE(os.stat(settings_path).st_mode))
    os.replace(temp_path, settings_path)
except Exception:
    try:
        os.unlink(temp_path)
    except FileNotFoundError:
        pass
    raise

print(f"CLAUDE_PLUGIN_ROOT -> {superpowers_root}")
print(f"Hook SessionStart  -> {hook_cmd}")
PYEOF

fi

# --- 3. Provisionador de Codex: skills compatibles ----------------------
if platform_is_selected codex; then
  mkdir -p "$CODEX_SKILLS_DST"
  CODEX_SKILL_LINKS="
commit-style|$BASE/skills/commit-style
brainstorming|$BASE/superpowers/skills/brainstorming
dispatching-parallel-agents|$BASE/superpowers/skills/dispatching-parallel-agents
executing-plans|$BASE/superpowers/skills/executing-plans
finishing-a-development-branch|$BASE/superpowers/skills/finishing-a-development-branch
receiving-code-review|$BASE/superpowers/skills/receiving-code-review
requesting-code-review|$BASE/superpowers/skills/requesting-code-review
subagent-driven-development|$BASE/superpowers/skills/subagent-driven-development
systematic-debugging|$BASE/superpowers/skills/systematic-debugging
test-driven-development|$BASE/superpowers/skills/test-driven-development
using-git-worktrees|$BASE/superpowers/skills/using-git-worktrees
using-superpowers|$BASE/superpowers/skills/using-superpowers
verification-before-completion|$BASE/superpowers/skills/verification-before-completion
writing-plans|$BASE/superpowers/skills/writing-plans
writing-skills|$BASE/superpowers/skills/writing-skills
context7-mcp|$BASE/context7/plugins/codex/context7/skills/context7-mcp
"

  echo "$CODEX_SKILL_LINKS" | while IFS='|' read -r name target; do
    [ -z "$name" ] && continue
    link="$CODEX_SKILLS_DST/$name"
    if [ ! -d "$target" ]; then
      echo "AVISO: falta $target - se omite $name para Codex"
      continue
    fi

    target_resolved="$(cd "$target" && pwd -P)"
    if [ -L "$link" ]; then
      link_resolved="$(resolve_symlink_dir "$link" || true)"
      if [ "$link_resolved" = "$target_resolved" ]; then
        echo "OK  Codex/$name ya apunta al destino administrado"
        continue
      fi
      echo "ERROR: $link es un symlink administrado por otra fuente" >&2
      exit 1
    elif [ -e "$link" ]; then
      echo "ERROR: $link existe y no es un symlink; no se reemplaza" >&2
      exit 1
    fi

    ln -s "$target" "$link"
    echo "OK  Codex/$name -> $target"
  done
fi

# --- 4. claude-mem: integraciones seleccionadas + worker ----------------
if platform_is_selected claude || platform_is_selected codex; then
  echo "==> Instalando claude-mem $CLAUDE_MEM_VERSION"
  if ! command -v npx >/dev/null 2>&1; then
    echo "ERROR: npx no esta disponible; instala Node.js y vuelve a ejecutar install.sh" >&2
    exit 1
  fi
  if platform_is_selected claude; then
    (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" install --ide claude-code </dev/null)
  fi
  if platform_is_selected codex; then
    (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" install --ide codex-cli </dev/null)
  fi
  (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" start)
fi

# --- 5. Context7 MCP por plataforma -------------------------------------
if platform_is_selected claude; then
  echo "==> Registrando Context7 para Claude (scope user)"
  if claude mcp get context7 >/dev/null 2>&1; then
    echo "OK  Context7 ya estaba registrado en Claude"
  else
    claude mcp add --transport http context7 https://mcp.context7.com/mcp -s user
  fi
fi

if platform_is_selected codex; then
  echo "==> Registrando Context7 para Codex"
  if codex mcp get context7 >/dev/null 2>&1; then
    echo "OK  Context7 ya estaba registrado en Codex"
  else
    codex mcp add context7 --url https://mcp.context7.com/mcp
  fi
fi

# --- 6. Resumen -----------------------------------------------------------
cat <<'EOF'

==> Instalacion terminada.
  - Los archivos de instrucciones locales se generaron desde
    PROJECT_INSTRUCTIONS.md segun las plataformas seleccionadas.
  - claude-mem quedo instalado y su worker fue iniciado.
  - Context7 funciona sin cuenta en el tier anonimo. Una API key es opcional.
  - Inicia una sesion nueva del agente para que cargue los nuevos archivos,
    skills y hooks. Los agentes leen esas instrucciones al comenzar la sesion.

==> Nota de versiones (importante en una maquina nueva):
  - Repos 'pinned' (superpowers, prompt-master, abogado-del-diablo,
    the-architect): quedan en el commit exacto fijado en third-party-repos.txt.
    Reproducibles: la maquina nueva tiene la misma version que la anterior.
  - Repos 'shallow' (context7, claude-token-efficient): traen el ULTIMO estado
    de la rama al momento de correr este script, NO una version fija. Si el
    autor upstream los cambio, aqui recibiras esa version nueva.
    Para fijarlos: en third-party-repos.txt cambia su modo a 'pinned' y pon un
    commit; luego borra su carpeta y vuelve a correr install.sh.
EOF
