#!/usr/bin/env bash
# Bootstrap multiplataforma de setup-ai-tools. Genera las instrucciones locales
# y ejecuta los provisionadores disponibles. Seguro al repetirse (idempotente).
set -euo pipefail

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DST="$HOME/.claude/skills"
SETTINGS="$HOME/.claude/settings.json"
CODEX_HOME="${CODEX_HOME:-$HOME/.codex}"
CODEX_SKILLS_DST="$CODEX_HOME/skills"
VERSIONS="$BASE/tool-versions.env"
PLATFORM_REGISTRY="$BASE/platforms.txt"
INSTRUCTIONS_SOURCE="$BASE/PROJECT_INSTRUCTIONS.md"
GENERATED_MARKER='<!-- Generated by setup-ai-tools from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->'
LEGACY_GENERATED_MARKER='<!-- Generated by setup-skills from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->'
STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
STATE_DIR="$STATE_HOME/setup-ai-tools"
STATE_FILE="$STATE_DIR/managed-roots"
STATE_MARKER="setup-ai-tools-managed-roots-v1"
LEGACY_STATE_DIR="$STATE_HOME/setup-skills"
LEGACY_STATE_FILE="$LEGACY_STATE_DIR/managed-roots"
LEGACY_STATE_MARKER="setup-skills-managed-roots-v1"
IMPORTED_LEGACY_STATE=0
MANAGED_ROOTS=""
SELECTED_PLATFORMS=""
MIGRATE_TOOLS=""
INSTALL_CONFLICTS=""
INSTRUCTIONS_ONLY=0

usage() {
  cat >&2 <<EOF
Uso: $0 [--platform <nombre>]... [--migrate-tool <nombre>]... [--instructions-only]

Sin --platform, detecta todos los CLI registrados disponibles en PATH.
--migrate-tool reemplaza symlinks externos solo para la herramienta indicada.
EOF
}

add_platform() {
  local platform="$1"
  if printf '%s\n' "$SELECTED_PLATFORMS" | grep -Fx "$platform" >/dev/null 2>&1; then
    return
  fi
  if [ -n "$SELECTED_PLATFORMS" ]; then
    SELECTED_PLATFORMS="$SELECTED_PLATFORMS
$platform"
  else
    SELECTED_PLATFORMS="$platform"
  fi
}

add_migrate_tool() {
  local tool="$1"
  if printf '%s\n' "$MIGRATE_TOOLS" | grep -Fx "$tool" >/dev/null 2>&1; then
    return
  fi
  if [ -n "$MIGRATE_TOOLS" ]; then
    MIGRATE_TOOLS="$MIGRATE_TOOLS
$tool"
  else
    MIGRATE_TOOLS="$tool"
  fi
}

migration_requested() {
  printf '%s\n' "$MIGRATE_TOOLS" | grep -Fx "$1" >/dev/null 2>&1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --platform)
      [ "$#" -ge 2 ] || { usage; exit 2; }
      add_platform "$2"
      shift 2
      ;;
    --instructions-only)
      INSTRUCTIONS_ONLY=1
      shift
      ;;
    --migrate-tool)
      [ "$#" -ge 2 ] || { usage; exit 2; }
      add_migrate_tool "$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
done

while IFS= read -r migrate_tool; do
  [ -n "$migrate_tool" ] || continue
  case "$migrate_tool" in
    superpowers) ;;
    *)
      echo "ERROR: migracion no implementada para: $migrate_tool" >&2
      exit 2
      ;;
  esac
done <<EOF
$MIGRATE_TOOLS
EOF

if [ ! -f "$PLATFORM_REGISTRY" ] || [ ! -f "$INSTRUCTIONS_SOURCE" ]; then
  echo "ERROR: faltan platforms.txt o PROJECT_INSTRUCTIONS.md" >&2
  exit 1
fi

if [ -z "$SELECTED_PLATFORMS" ]; then
  SELECTED_PLATFORMS="$(
    while IFS='|' read -r platform cli_command version_argument instructions_file detail; do
      [ -n "$platform" ] || continue
      [ "${platform#\#}" = "$platform" ] || continue
      if command -v "$cli_command" >/dev/null 2>&1; then
        printf '%s\n' "$platform"
      fi
    done < "$PLATFORM_REGISTRY"
  )"
fi

if [ -z "$SELECTED_PLATFORMS" ]; then
  echo "ERROR: no se detecto ningun CLI registrado; usa --platform <nombre>" >&2
  exit 1
fi

generate_instruction_file() {
  local platform="$1"
  local instructions_file destination temporary first_line

  instructions_file="$(awk -F'|' -v wanted="$platform" '
    $1 !~ /^#/ && $1 == wanted { print $4; found = 1; exit }
    END { if (!found) exit 1 }
  ' "$PLATFORM_REGISTRY")" || {
    echo "ERROR: plataforma no registrada: $platform" >&2
    return 1
  }

  case "$instructions_file" in
    ''|*/*|*[!A-Za-z0-9._-]*)
      echo "ERROR: archivo de instrucciones invalido para $platform: $instructions_file" >&2
      return 1
      ;;
  esac

  destination="$BASE/$instructions_file"
  if [ -L "$destination" ]; then
    echo "ERROR: $destination es un symlink; no se reemplaza" >&2
    return 1
  fi
  if [ -e "$destination" ]; then
    if [ ! -f "$destination" ]; then
      echo "ERROR: $destination existe y no es un archivo regular" >&2
      return 1
    fi
    first_line="$(sed -n '1p' "$destination")"
    case "$first_line" in
      "$GENERATED_MARKER"|"$LEGACY_GENERATED_MARKER") ;;
      *)
        echo "ERROR: $destination no es administrado por setup-ai-tools; se conserva" >&2
        return 1
        ;;
    esac
  fi

  temporary="$(mktemp "$BASE/.instructions.XXXXXX")"
  {
    printf '%s\n\n' "$GENERATED_MARKER"
    cat "$INSTRUCTIONS_SOURCE"
  } > "$temporary"

  if [ -f "$destination" ] && cmp -s "$temporary" "$destination"; then
    rm -f "$temporary"
    echo "OK  $instructions_file ya esta actualizado para $platform"
    return
  fi

  mv "$temporary" "$destination"
  echo "OK  $instructions_file generado para $platform"
}

printf '%s\n' "$SELECTED_PLATFORMS" | while IFS= read -r platform; do
  [ -n "$platform" ] || continue
  generate_instruction_file "$platform"
done

if [ "$INSTRUCTIONS_ONLY" -eq 1 ]; then
  echo "==> Archivos de instrucciones listos"
  exit 0
fi

if [ ! -x "$BASE/verify-compatibility.sh" ]; then
  echo "ERROR: falta el verificador ejecutable $BASE/verify-compatibility.sh" >&2
  exit 1
fi

verify_selected_platforms() {
  local phase="$1"
  local result output
  printf '%s\n' "$SELECTED_PLATFORMS" | while IFS= read -r platform; do
    [ -n "$platform" ] || continue
    if [ "$phase" = "pre" ]; then
      if output="$("$BASE/verify-compatibility.sh" --platform "$platform" --phase "$phase" 2>&1)"; then
        continue
      else
        result=$?
      fi
      if [ "$result" -eq 2 ]; then
        continue
      fi
      printf '%s\n' "$output" >&2
      return "$result"
    fi

    if "$BASE/verify-compatibility.sh" --platform "$platform" --phase "$phase"; then
      continue
    else
      result=$?
    fi
    if [ "$result" -eq 2 ]; then
      echo "AVISO: $platform requiere adaptadores; se continuara con lo disponible" >&2
    else
      return "$result"
    fi
  done
}

platform_is_selected() {
  printf '%s\n' "$SELECTED_PLATFORMS" | grep -Fx "$1" >/dev/null 2>&1
}

add_managed_root() {
  local root="$1"
  [ -n "$root" ] || return
  case "$root" in
    /*) ;;
    *)
      echo "ERROR: ruta administrada invalida: $root" >&2
      return 1
      ;;
  esac
  if printf '%s\n' "$MANAGED_ROOTS" | grep -Fx "$root" >/dev/null 2>&1; then
    return
  fi
  if [ -n "$MANAGED_ROOTS" ]; then
    MANAGED_ROOTS="$MANAGED_ROOTS
$root"
  else
    MANAGED_ROOTS="$root"
  fi
}

load_install_state_file() {
  local state_file="$1"
  local expected_marker="$2"
  local marker root count=0
  if [ -L "$state_file" ]; then
    echo "ERROR: $state_file es un symlink; no se utiliza" >&2
    return 1
  fi
  if [ ! -e "$state_file" ]; then
    return
  fi
  if [ ! -f "$state_file" ]; then
    echo "ERROR: $state_file existe y no es un archivo regular" >&2
    return 1
  fi

  {
    IFS= read -r marker || {
      echo "ERROR: estado de instalacion vacio: $state_file" >&2
      return 1
    }
    if [ "$marker" != "$expected_marker" ]; then
      echo "ERROR: estado de instalacion no reconocido: $state_file" >&2
      return 1
    fi
    while IFS= read -r root; do
      [ -n "$root" ] || {
        echo "ERROR: ruta vacia en $state_file" >&2
        return 1
      }
      add_managed_root "$root"
      count=$((count + 1))
    done
  } < "$state_file"

  if [ "$count" -eq 0 ]; then
    echo "ERROR: $state_file no declara ninguna ruta administrada" >&2
    return 1
  fi
}

load_install_state() {
  if [ -e "$STATE_FILE" ] || [ -L "$STATE_FILE" ]; then
    load_install_state_file "$STATE_FILE" "$STATE_MARKER"
    return
  fi

  if [ -e "$LEGACY_STATE_FILE" ] || [ -L "$LEGACY_STATE_FILE" ]; then
    load_install_state_file "$LEGACY_STATE_FILE" "$LEGACY_STATE_MARKER"
    IMPORTED_LEGACY_STATE=1
    echo "==> Estado anterior importado desde: $LEGACY_STATE_DIR"
  fi
}

import_legacy_migration_log() {
  local old_log="$LEGACY_STATE_DIR/migrations.log"
  local new_log="$STATE_DIR/migrations.log"
  [ "$IMPORTED_LEGACY_STATE" -eq 1 ] || return 0
  [ -e "$old_log" ] || [ -L "$old_log" ] || return 0

  if [ -L "$old_log" ] || [ ! -f "$old_log" ]; then
    echo "ERROR: historial anterior invalido: $old_log" >&2
    return 1
  fi
  if [ -e "$new_log" ] || [ -L "$new_log" ]; then
    echo "AVISO: ya existe $new_log; el historial anterior se conserva en $old_log" >&2
    return 0
  fi

  mkdir -p "$STATE_DIR"
  cp "$old_log" "$new_log"
  chmod 600 "$new_log"
  echo "OK  historial de migraciones importado desde setup-skills"
}

LEGACY_ROOT=""
LEGACY_MATCHES=0
LEGACY_CONFLICT=0

consider_legacy_symlink() {
  local link="$1"
  local relative_target="$2"
  local raw suffix candidate
  [ -L "$link" ] || return 0
  raw="$(readlink "$link")"
  case "$raw" in /*) ;; *) return 0 ;; esac
  [ ! -e "$raw" ] || return 0
  suffix="/$relative_target"
  case "$raw" in
    *"$suffix") candidate="${raw%"$suffix"}" ;;
    *) return 0 ;;
  esac
  [ -n "$candidate" ] || return 0
  [ "$candidate" != "/" ] || return 0
  if [ -n "$LEGACY_ROOT" ] && [ "$LEGACY_ROOT" != "$candidate" ]; then
    LEGACY_CONFLICT=1
    return 0
  fi
  LEGACY_ROOT="$candidate"
  LEGACY_MATCHES=$((LEGACY_MATCHES + 1))
}

discover_legacy_root() {
  [ -z "$MANAGED_ROOTS" ] || return 0

  consider_legacy_symlink "$SKILLS_DST/commit-style" "skills/commit-style"
  consider_legacy_symlink "$SKILLS_DST/using-superpowers" "superpowers/skills/using-superpowers"
  consider_legacy_symlink "$CODEX_SKILLS_DST/commit-style" "skills/commit-style"
  consider_legacy_symlink "$CODEX_SKILLS_DST/using-superpowers" "superpowers/skills/using-superpowers"

  if [ "$LEGACY_CONFLICT" -eq 0 ] && [ "$LEGACY_MATCHES" -ge 2 ]; then
    add_managed_root "$LEGACY_ROOT"
    echo "==> Instalacion anterior detectada en: $LEGACY_ROOT"
  fi
  return 0
}

write_install_state() {
  local temporary root
  add_managed_root "$BASE"
  if [ -L "$STATE_FILE" ]; then
    echo "ERROR: $STATE_FILE es un symlink; no se reemplaza" >&2
    return 1
  fi
  if [ -e "$STATE_FILE" ] && [ ! -f "$STATE_FILE" ]; then
    echo "ERROR: $STATE_FILE existe y no es un archivo regular" >&2
    return 1
  fi
  mkdir -p "$STATE_DIR"
  temporary="$(mktemp "$STATE_DIR/.managed-roots.XXXXXX")"
  {
    printf '%s\n' "$STATE_MARKER"
    printf '%s\n' "$BASE"
    while IFS= read -r root; do
      [ -n "$root" ] || continue
      [ "$root" = "$BASE" ] && continue
      printf '%s\n' "$root"
    done <<EOF
$MANAGED_ROOTS
EOF
  } > "$temporary"
  chmod 600 "$temporary"
  mv "$temporary" "$STATE_FILE"
  echo "OK  ruta administrada registrada: $BASE"
}

load_install_state
import_legacy_migration_log
discover_legacy_root

if platform_is_selected claude || platform_is_selected codex; then
  if [ ! -f "$VERSIONS" ]; then
    echo "ERROR: no se encontro $VERSIONS" >&2
    exit 1
  fi

  # shellcheck disable=SC1090
  . "$VERSIONS"
  : "${CLAUDE_MEM_VERSION:?Falta CLAUDE_MEM_VERSION en tool-versions.env}"
  : "${GRAPHIFY_VERSION:?Falta GRAPHIFY_VERSION en tool-versions.env}"
fi

verify_selected_platforms pre

echo "==> Usando setup-ai-tools en: $BASE"

normalize_git_url() {
  local value="${1%/}"
  printf '%s\n' "${value%.git}"
}

is_plain_semver() {
  awk -v version="$1" 'BEGIN { exit (version ~ /^[0-9]+\.[0-9]+\.[0-9]+$/ ? 0 : 1) }'
}

semver_is_greater() {
  awk -v candidate="$1" -v reference="$2" '
    BEGIN {
      split(candidate, candidate_parts, ".")
      split(reference, reference_parts, ".")
      for (part_index = 1; part_index <= 3; part_index++) {
        candidate_part = candidate_parts[part_index] + 0
        reference_part = reference_parts[part_index] + 0
        if (candidate_part > reference_part) exit 0
        if (candidate_part < reference_part) exit 1
      }
      exit 1
    }
  '
}

highest_installed_claude_mem_version() {
  local cache_root candidate version highest=""

  for cache_root in \
    "$HOME/.claude/plugins/cache/thedotmack/claude-mem" \
    "$CODEX_HOME/plugins/cache/claude-mem-local/claude-mem"; do
    [ -d "$cache_root" ] || continue
    for candidate in "$cache_root"/*; do
      [ -d "$candidate" ] || continue
      version="${candidate##*/}"
      is_plain_semver "$version" || continue
      if [ -z "$highest" ] || semver_is_greater "$version" "$highest"; then
        highest="$version"
      fi
    done
  done

  printf '%s\n' "$highest"
}

validate_repo_source() {
  local name="$1"
  local dest="$2"
  local required

  case "$name" in
    superpowers) required="skills/using-superpowers/SKILL.md" ;;
    prompt-master) required="SKILL.md" ;;
    abogado-del-diablo) required="skills/abogado-del-diablo/SKILL.md" ;;
    the-architect) required="CLAUDE.md" ;;
    context7) required="packages/mcp/package.json" ;;
    claude-token-efficient) required="CLAUDE.md" ;;
    *) required="README.md" ;;
  esac

  if [ ! -f "$dest/$required" ]; then
    echo "ERROR: $name no contiene el archivo esperado: $required" >&2
    return 1
  fi
}

ensure_clean_tracked_state() {
  local name="$1"
  local dest="$2"
  if ! git -C "$dest" diff --quiet || ! git -C "$dest" diff --cached --quiet; then
    echo "ERROR: $name tiene cambios rastreados; guardalos antes de reconciliar la version" >&2
    return 1
  fi
}

reconcile_repo() {
  local name="$1"
  local url="$2"
  local branch="$3"
  local commit="$4"
  local mode="$5"
  local dest="$BASE/$name"
  local current_url current_commit desired_commit

  case "$mode" in
    pinned)
      if [ -z "$commit" ] || [ "$commit" = "-" ]; then
        echo "ERROR: $name esta en modo pinned pero no declara commit" >&2
        return 1
      fi
      ;;
    shallow) ;;
    *)
      echo "ERROR: modo desconocido para $name: $mode" >&2
      return 1
      ;;
  esac

  if [ -e "$dest" ] && [ ! -d "$dest/.git" ]; then
    echo "ERROR: $dest existe pero no es un repositorio Git administrable" >&2
    return 1
  fi

  if [ ! -d "$dest/.git" ]; then
    if [ "$mode" = "shallow" ]; then
      echo "==> clone shallow $name ($branch)"
      git clone --depth 1 --branch "$branch" "$url" "$dest"
    else
      echo "==> clone $name (pinned $commit)"
      git clone "$url" "$dest"
      git -C "$dest" checkout --detach "$commit"
    fi
    validate_repo_source "$name" "$dest"
    return
  fi

  current_url="$(git -C "$dest" config --get remote.origin.url || true)"
  if [ -z "$current_url" ] || [ "$(normalize_git_url "$current_url")" != "$(normalize_git_url "$url")" ]; then
    echo "ERROR: $name existe pero su origin no coincide" >&2
    echo "  Actual:   ${current_url:-(sin origin)}" >&2
    echo "  Esperado: $url" >&2
    return 1
  fi

  current_commit="$(git -C "$dest" rev-parse HEAD)"
  if [ "$mode" = "pinned" ]; then
    desired_commit="$commit"
    if [ "$current_commit" = "$desired_commit" ]; then
      echo "OK  $name coincide con el commit fijado ($desired_commit)"
      validate_repo_source "$name" "$dest"
      return
    fi

    ensure_clean_tracked_state "$name" "$dest"
    if ! git -C "$dest" cat-file -e "$desired_commit^{commit}" 2>/dev/null; then
      git -C "$dest" fetch origin "$desired_commit"
    fi
  else
    git -C "$dest" fetch origin "$branch"
    desired_commit="$(git -C "$dest" rev-parse FETCH_HEAD)"
    if [ "$current_commit" = "$desired_commit" ]; then
      echo "OK  $name ya coincide con el ultimo commit de $branch ($desired_commit)"
      validate_repo_source "$name" "$dest"
      return
    fi
    ensure_clean_tracked_state "$name" "$dest"
  fi

  echo "==> Reconciliando $name: $current_commit -> $desired_commit"
  git -C "$dest" checkout --detach "$desired_commit"
  validate_repo_source "$name" "$dest"
}

resolve_symlink_dir() {
  local link="$1"
  local raw candidate
  raw="$(readlink "$link")"
  case "$raw" in
    /*) candidate="$raw" ;;
    *) candidate="$(dirname "$link")/$raw" ;;
  esac
  (cd "$candidate" 2>/dev/null && pwd -P)
}

symlink_uses_managed_root() {
  local link="$1"
  local target="$2"
  local raw relative_target root
  raw="$(readlink "$link")"
  relative_target="${target#"$BASE"/}"
  [ "$relative_target" != "$target" ] || return 1

  while IFS= read -r root; do
    [ -n "$root" ] || continue
    if [ "$raw" = "$root/$relative_target" ]; then
      return 0
    fi
  done <<EOF
$MANAGED_ROOTS
EOF
  return 1
}

ensure_skill_link() {
  local platform="$1"
  local tool="$2"
  local label="$3"
  local link="$4"
  local target="$5"
  local target_resolved link_resolved

  target_resolved="$(cd "$target" && pwd -P)"
  if [ -L "$link" ]; then
    link_resolved="$(resolve_symlink_dir "$link" || true)"
    if [ "$link_resolved" = "$target_resolved" ]; then
      echo "OK  $label ya apunta al destino administrado"
      return
    fi
    if symlink_uses_managed_root "$link" "$target"; then
      echo "MIG $label: $(readlink "$link") -> $target"
      ln -sfn "$target" "$link"
      return
    fi
    if migration_requested "$tool"; then
      append_migration_record "$platform" "$tool" "$(readlink "$link")" "-" "-" "$target"
      echo "MIG $label externo: $(readlink "$link") -> $target"
      ln -sfn "$target" "$link"
      return
    fi
    add_install_conflict "$platform/$tool: se conserva $link -> $(readlink "$link")"
    echo "AVISO: $link pertenece a otra instalacion; se conserva y se omite $label" >&2
    return 0
  fi
  if [ -e "$link" ]; then
    if migration_requested "$tool"; then
      echo "ERROR: $link es una carpeta o archivo real; la migracion nunca lo reemplaza" >&2
      return 1
    fi
    add_install_conflict "$platform/$tool: se conserva el destino real $link"
    echo "AVISO: $link es un destino real; se conserva y se omite $label" >&2
    return 0
  fi

  ln -s "$target" "$link"
  echo "OK  $label -> $target"
}

install_managed_instruction_block() {
  local platform="$1"
  local feature="$2"
  local destination="$3"
  local source="$4"
  local override="${5:-}"
  local status
  local marker_begin="# >>> setup-ai-tools: $feature >>>"
  local marker_end="# <<< setup-ai-tools: $feature <<<"

  if [ ! -f "$source" ]; then
    echo "ERROR: falta la fuente de $feature: $source" >&2
    return 1
  fi

  if [ -n "$override" ] && [ -f "$override" ] && [ -s "$override" ]; then
    add_install_conflict "$platform/$feature: $(basename "$override") no vacio puede ocultar $destination"
    echo "AVISO: $override no vacio puede impedir que $platform lea $destination" >&2
  fi

  if [ -L "$destination" ]; then
    add_install_conflict "$platform/$feature: $(basename "$destination") es un symlink; se conserva"
    echo "AVISO: $destination es un symlink; se conserva y se omite $feature" >&2
    return 0
  fi
  if [ -e "$destination" ] && [ ! -f "$destination" ]; then
    add_install_conflict "$platform/$feature: $(basename "$destination") existe y no es un archivo regular; se conserva"
    echo "AVISO: $destination existe y no es un archivo regular; se conserva y se omite $feature" >&2
    return 0
  fi

  if python3 - "$destination" "$source" "$marker_begin" "$marker_end" "$feature" <<'PYEOF'
import os
import re
import stat
import sys
import tempfile

destination_path, source_path, begin, end, feature = sys.argv[1:]

with open(source_path, encoding="utf-8") as f:
    source = f.read()

if begin in source or end in source:
    print(
        f"ERROR: la fuente de {feature} contiene marcadores administrados",
        file=sys.stderr,
    )
    raise SystemExit(4)

if os.path.exists(destination_path):
    with open(destination_path, encoding="utf-8") as f:
        current = f.read()
else:
    current = ""

lines = current.splitlines(keepends=True)
line_contents = [line.rstrip("\r\n") for line in lines]
begin_indexes = [
    index for index, line in enumerate(line_contents) if line == begin
]
end_indexes = [
    index for index, line in enumerate(line_contents) if line == end
]
has_marker_variant = any(
    line.startswith(begin) and line != begin for line in line_contents
) or any(
    line.startswith(end) and line != end for line in line_contents
)

managed_begin = re.compile(r"^# >>> setup-ai-tools: ([A-Za-z0-9._-]+) >>>$")
managed_end = re.compile(r"^# <<< setup-ai-tools: ([A-Za-z0-9._-]+) <<<$")
active = None
all_markers_valid = True
for line in line_contents:
    begin_match = managed_begin.fullmatch(line)
    end_match = managed_end.fullmatch(line)
    if line.startswith("# >>> setup-ai-tools:") and begin_match is None:
        all_markers_valid = False
        break
    if line.startswith("# <<< setup-ai-tools:") and end_match is None:
        all_markers_valid = False
        break
    if begin_match:
        if active is not None:
            all_markers_valid = False
            break
        active = begin_match.group(1)
    elif end_match:
        if active != end_match.group(1):
            all_markers_valid = False
            break
        active = None
if active is not None:
    all_markers_valid = False

if has_marker_variant or not all_markers_valid:
    print(
        f"AVISO: {destination_path} contiene marcadores administrados corruptos; se conserva",
        file=sys.stderr,
    )
    raise SystemExit(3)
elif not begin_indexes and not end_indexes:
    prefix = current
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    updated = prefix + begin + "\n" + source
    if not updated.endswith(("\n", "\r")):
        updated += "\n"
    updated += end + "\n"
elif len(begin_indexes) == 1 and len(end_indexes) == 1 and begin_indexes[0] < end_indexes[0]:
    source_block = source
    if source_block and not source_block.endswith(("\n", "\r")):
        source_block += "\n"
    updated = "".join(lines[:begin_indexes[0]])
    updated += begin + "\n" + source_block + end + "\n"
    updated += "".join(lines[end_indexes[0] + 1:])
else:
    print(
        f"AVISO: {destination_path} contiene marcadores administrados corruptos; se conserva",
        file=sys.stderr,
    )
    raise SystemExit(3)

directory = os.path.dirname(destination_path)
os.makedirs(directory, exist_ok=True)
fd, temporary = tempfile.mkstemp(prefix=".instructions.", suffix=".md", dir=directory)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        f.write(updated)
        f.flush()
        os.fsync(f.fileno())
    if os.path.exists(destination_path):
        os.chmod(temporary, stat.S_IMODE(os.stat(destination_path).st_mode))
    os.replace(temporary, destination_path)
except Exception:
    try:
        os.unlink(temporary)
    except FileNotFoundError:
        pass
    raise
PYEOF
  then
    echo "OK  $feature actualizado en $destination"
    return 0
  else
    status=$?
  fi

  if [ "$status" -eq 3 ]; then
    add_install_conflict "$platform/$feature: marcadores administrados corruptos en $(basename "$destination"); se conserva"
    return 0
  fi
  return "$status"
}

add_install_conflict() {
  local detail="$1"
  if printf '%s\n' "$INSTALL_CONFLICTS" | grep -Fx "$detail" >/dev/null 2>&1; then
    return
  fi
  if [ -n "$INSTALL_CONFLICTS" ]; then
    INSTALL_CONFLICTS="$INSTALL_CONFLICTS
$detail"
  else
    INSTALL_CONFLICTS="$detail"
  fi
}

append_migration_record() {
  local platform="$1"
  local tool="$2"
  local previous_target="$3"
  local previous_origin="$4"
  local previous_commit="$5"
  local new_target="$6"
  local log_file="$STATE_DIR/migrations.log"
  local temporary

  if [ -L "$log_file" ]; then
    echo "ERROR: $log_file es un symlink; no se registra la migracion" >&2
    return 1
  fi
  if [ -e "$log_file" ] && [ ! -f "$log_file" ]; then
    echo "ERROR: $log_file existe y no es un archivo regular" >&2
    return 1
  fi
  mkdir -p "$STATE_DIR"
  temporary="$(mktemp "$STATE_DIR/.migrations.XXXXXX")"
  if [ -f "$log_file" ]; then
    cp "$log_file" "$temporary"
  fi
  {
    printf '%s\n' '---'
    printf 'timestamp=%s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    printf 'platform=%s\n' "$platform"
    printf 'tool=%s\n' "$tool"
    printf 'previous_target=%s\n' "$previous_target"
    printf 'previous_origin=%s\n' "$previous_origin"
    printf 'previous_commit=%s\n' "$previous_commit"
    printf 'new_target=%s\n' "$new_target"
  } >> "$temporary"
  chmod 600 "$temporary"
  mv "$temporary" "$log_file"
}

SUPERPOWERS_CLAUDE_ROOT="$BASE/superpowers"
SUPERPOWERS_CODEX_ROOT="$BASE/superpowers"
SKIP_SUPERPOWERS_CLAUDE=0
SKIP_SUPERPOWERS_CODEX=0

set_superpowers_root() {
  local platform="$1"
  local root="$2"
  case "$platform" in
    claude) SUPERPOWERS_CLAUDE_ROOT="$root" ;;
    codex) SUPERPOWERS_CODEX_ROOT="$root" ;;
  esac
}

skip_superpowers() {
  local platform="$1"
  case "$platform" in
    claude) SKIP_SUPERPOWERS_CLAUDE=1 ;;
    codex) SKIP_SUPERPOWERS_CODEX=1 ;;
  esac
}

superpowers_is_skipped() {
  case "$1" in
    claude) [ "$SKIP_SUPERPOWERS_CLAUDE" -eq 1 ] ;;
    codex) [ "$SKIP_SUPERPOWERS_CODEX" -eq 1 ] ;;
    *) return 1 ;;
  esac
}

validate_superpowers_migration_destinations() {
  local platform="$1"
  local skills_dir="$2"
  local name link
  while IFS= read -r name; do
    [ -n "$name" ] || continue
    link="$skills_dir/$name"
    if [ -e "$link" ] && [ ! -L "$link" ]; then
      echo "ERROR: no se puede migrar $platform/superpowers: $link es un destino real" >&2
      echo "Muevelo manualmente y vuelve a ejecutar el instalador" >&2
      return 1
    fi
  done <<'EOF'
brainstorming
dispatching-parallel-agents
executing-plans
finishing-a-development-branch
receiving-code-review
requesting-code-review
subagent-driven-development
systematic-debugging
test-driven-development
using-git-worktrees
using-superpowers
verification-before-completion
writing-plans
writing-skills
EOF
}

prepare_superpowers_for_platform() {
  local platform="$1"
  local link="$2"
  local managed_target="$BASE/superpowers/skills/using-superpowers"
  local raw suffix external_root external_origin external_commit expected_origin expected_commit detail

  if migration_requested superpowers; then
    validate_superpowers_migration_destinations "$platform" "$(dirname "$link")"
  fi

  [ -e "$link" ] || [ -L "$link" ] || return 0

  if [ ! -L "$link" ]; then
    if migration_requested superpowers; then
      echo "ERROR: $link es un destino real; mueve esa instalacion manualmente antes de migrar" >&2
      return 1
    fi
    detail="$platform/superpowers: destino real existente en $link; se conserva"
    add_install_conflict "$detail"
    skip_superpowers "$platform"
    return 0
  fi

  if symlink_uses_managed_root "$link" "$managed_target"; then
    return 0
  fi

  raw="$(readlink "$link")"
  if [ "$(resolve_symlink_dir "$link" || true)" = "$(cd "$managed_target" && pwd -P)" ]; then
    return 0
  fi

  suffix="/skills/using-superpowers"
  case "$raw" in
    *"$suffix") external_root="${raw%"$suffix"}" ;;
    *) external_root="" ;;
  esac
  external_origin="-"
  external_commit="-"
  if [ -n "$external_root" ] && [ -d "$external_root/.git" ]; then
    external_origin="$(git -C "$external_root" config --get remote.origin.url || true)"
    external_commit="$(git -C "$external_root" rev-parse HEAD 2>/dev/null || true)"
  fi
  expected_origin="$(git -C "$BASE/superpowers" config --get remote.origin.url)"
  expected_commit="$(git -C "$BASE/superpowers" rev-parse HEAD)"

  if [ -n "$external_root" ] \
    && [ "$(normalize_git_url "$external_origin")" = "$(normalize_git_url "$expected_origin")" ] \
    && [ "$external_commit" = "$expected_commit" ] \
    && [ -z "$(git -C "$external_root" status --porcelain)" ]; then
    set_superpowers_root "$platform" "$external_root"
    echo "REUSE $platform/superpowers desde $external_root ($external_commit)"
    return 0
  fi

  if migration_requested superpowers; then
    append_migration_record "$platform" superpowers "${external_root:-$raw}" \
      "$external_origin" "$external_commit" "$BASE/superpowers"
    echo "==> Migracion autorizada para $platform/superpowers"
    return 0
  fi

  detail="$platform/superpowers: externa=${external_origin}@${external_commit}, declarada=${expected_origin}@${expected_commit}; se conserva"
  add_install_conflict "$detail"
  skip_superpowers "$platform"
  echo "AVISO: Superpowers externo difiere para $platform; se conserva y se omite" >&2
}

# --- 0. Clonar repos de terceros desde el manifiesto -------------------
# Solo referencias: el repo propio no versiona el codigo de terceros, lo
# clona aqui. Lee third-party-repos.txt (nombre|url|branch|commit|modo).
MANIFEST="$BASE/third-party-repos.txt"
if [ -f "$MANIFEST" ]; then
  echo "==> Validando repos de terceros (manifiesto: third-party-repos.txt)"
  while IFS='|' read -r name url branch commit mode; do
    case "$name" in
      ''|\#*) continue ;;  # ignora lineas vacias y comentarios
    esac
    reconcile_repo "$name" "$url" "$branch" "$commit" "$mode"
  done < "$MANIFEST"
else
  echo "ERROR: no se encontro $MANIFEST" >&2
  exit 1
fi

verify_selected_platforms post

# --- Graphify: solo CLI aislado; no usar sus instaladores de plataforma ---
install_graphify_cli() {
  echo "==> Instalando Graphify $GRAPHIFY_VERSION con uv y Python 3.12"
  if ! command -v uv >/dev/null 2>&1; then
    echo "ERROR: uv no esta disponible; instalalo para provisionar Graphify" >&2
    return 1
  fi
  uv tool install --python 3.12 "graphifyy==$GRAPHIFY_VERSION"
}

if platform_is_selected claude || platform_is_selected codex; then
  install_graphify_cli
fi

if platform_is_selected claude; then
  prepare_superpowers_for_platform claude "$SKILLS_DST/using-superpowers"
fi
if platform_is_selected codex; then
  prepare_superpowers_for_platform codex "$CODEX_SKILLS_DST/using-superpowers"
fi

# --- 1. Provisionador actual de Claude: symlinks de skills -------------
if platform_is_selected claude; then
mkdir -p "$SKILLS_DST"

install_managed_instruction_block \
  claude \
  claude-mem-selective-recall \
  "$HOME/.claude/CLAUDE.md" \
  "$BASE/rules/claude-mem-selective-recall.md"

# macOS trae bash 3.2 (sin arrays asociativos), por eso usamos pares "name|target".
SKILL_LINKS="
commit-style|commit-style|$BASE/skills/commit-style
graphify|graphify|$BASE/skills/graphify
cyber-neo|cyber-neo|$BASE/skills/cyber-neo
prompt-master|prompt-master|$BASE/prompt-master
abogado-del-diablo|abogado-del-diablo|$BASE/abogado-del-diablo/skills/abogado-del-diablo
superpowers|brainstorming|$SUPERPOWERS_CLAUDE_ROOT/skills/brainstorming
superpowers|dispatching-parallel-agents|$SUPERPOWERS_CLAUDE_ROOT/skills/dispatching-parallel-agents
superpowers|executing-plans|$SUPERPOWERS_CLAUDE_ROOT/skills/executing-plans
superpowers|finishing-a-development-branch|$SUPERPOWERS_CLAUDE_ROOT/skills/finishing-a-development-branch
superpowers|receiving-code-review|$SUPERPOWERS_CLAUDE_ROOT/skills/receiving-code-review
superpowers|requesting-code-review|$SUPERPOWERS_CLAUDE_ROOT/skills/requesting-code-review
superpowers|subagent-driven-development|$SUPERPOWERS_CLAUDE_ROOT/skills/subagent-driven-development
superpowers|systematic-debugging|$SUPERPOWERS_CLAUDE_ROOT/skills/systematic-debugging
superpowers|test-driven-development|$SUPERPOWERS_CLAUDE_ROOT/skills/test-driven-development
superpowers|using-git-worktrees|$SUPERPOWERS_CLAUDE_ROOT/skills/using-git-worktrees
superpowers|using-superpowers|$SUPERPOWERS_CLAUDE_ROOT/skills/using-superpowers
superpowers|verification-before-completion|$SUPERPOWERS_CLAUDE_ROOT/skills/verification-before-completion
superpowers|writing-plans|$SUPERPOWERS_CLAUDE_ROOT/skills/writing-plans
superpowers|writing-skills|$SUPERPOWERS_CLAUDE_ROOT/skills/writing-skills
"

while IFS='|' read -r tool name target; do
  [ -z "$name" ] && continue
  if [ "$tool" = "superpowers" ] && superpowers_is_skipped claude; then
    continue
  fi
  link="$SKILLS_DST/$name"
  if [ ! -d "$target" ]; then
    echo "AVISO: falta $target (submodulo/repo no clonado?) - se omite $name"
    continue
  fi

  ensure_skill_link claude "$tool" "$name" "$link" "$target"
done <<EOF
$SKILL_LINKS
EOF

# --- 2. Superpowers: CLAUDE_PLUGIN_ROOT y hook SessionStart -------------
if ! superpowers_is_skipped claude; then
echo "==> Actualizando settings.json (CLAUDE_PLUGIN_ROOT + hook de superpowers)"
python3 - "$SETTINGS" "$SUPERPOWERS_CLAUDE_ROOT" <<'PYEOF'
import json
import os
import stat
import sys
import tempfile

settings_path, superpowers_root = sys.argv[1], sys.argv[2]

if os.path.exists(settings_path):
    with open(settings_path, encoding="utf-8") as f:
        data = json.load(f)
else:
    data = {}

if not isinstance(data, dict):
    raise SystemExit("settings.json debe contener un objeto JSON")

env = data.setdefault("env", {})
if not isinstance(env, dict):
    raise SystemExit("settings.json: 'env' debe ser un objeto")
env["CLAUDE_PLUGIN_ROOT"] = superpowers_root

hooks = data.setdefault("hooks", {})
if not isinstance(hooks, dict):
    raise SystemExit("settings.json: 'hooks' debe ser un objeto")

session_start = hooks.setdefault("SessionStart", [])
if not isinstance(session_start, list):
    raise SystemExit("settings.json: 'hooks.SessionStart' debe ser una lista")

hook_cmd = f"{superpowers_root}/hooks/run-hook.cmd session-start"
managed_hook = None
target_group = None
for index, group in enumerate(session_start):
    if not isinstance(group, dict):
        raise SystemExit(f"settings.json: SessionStart[{index}] debe ser un objeto")
    group_hooks = group.get("hooks")
    if group_hooks is None:
        continue
    if not isinstance(group_hooks, list):
        raise SystemExit(f"settings.json: SessionStart[{index}].hooks debe ser una lista")
    if target_group is None:
        target_group = group
    for hook_index, item in enumerate(group_hooks):
        if not isinstance(item, dict):
            raise SystemExit(
                f"settings.json: SessionStart[{index}].hooks[{hook_index}] debe ser un objeto"
            )
        if (
            item.get("type") == "command"
            and "run-hook.cmd session-start" in item.get("command", "")
        ):
            managed_hook = item

if managed_hook is not None:
    managed_hook["command"] = hook_cmd
else:
    if target_group is None:
        target_group = {"hooks": []}
        session_start.append(target_group)
    target_group["hooks"].append({"type": "command", "command": hook_cmd})

settings_dir = os.path.dirname(settings_path)
os.makedirs(settings_dir, exist_ok=True)
fd, temp_path = tempfile.mkstemp(prefix=".settings.", suffix=".json", dir=settings_dir)
try:
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
        f.flush()
        os.fsync(f.fileno())
    if os.path.exists(settings_path):
        os.chmod(temp_path, stat.S_IMODE(os.stat(settings_path).st_mode))
    os.replace(temp_path, settings_path)
except Exception:
    try:
        os.unlink(temp_path)
    except FileNotFoundError:
        pass
    raise

print(f"CLAUDE_PLUGIN_ROOT -> {superpowers_root}")
print(f"Hook SessionStart  -> {hook_cmd}")
PYEOF
else
  echo "AVISO: configuracion y hook de Superpowers para Claude omitidos por conflicto" >&2
fi

fi

# --- 3. Provisionador de Codex: skills compatibles ----------------------
if platform_is_selected codex; then
  mkdir -p "$CODEX_SKILLS_DST"
  CODEX_SKILL_LINKS="
commit-style|commit-style|$BASE/skills/commit-style
graphify|graphify|$BASE/skills/graphify
prompt-master|prompt-master|$BASE/adapters/codex/prompt-master
abogado-del-diablo|abogado-del-diablo|$BASE/adapters/codex/abogado-del-diablo
superpowers|brainstorming|$SUPERPOWERS_CODEX_ROOT/skills/brainstorming
superpowers|dispatching-parallel-agents|$SUPERPOWERS_CODEX_ROOT/skills/dispatching-parallel-agents
superpowers|executing-plans|$SUPERPOWERS_CODEX_ROOT/skills/executing-plans
superpowers|finishing-a-development-branch|$SUPERPOWERS_CODEX_ROOT/skills/finishing-a-development-branch
superpowers|receiving-code-review|$SUPERPOWERS_CODEX_ROOT/skills/receiving-code-review
superpowers|requesting-code-review|$SUPERPOWERS_CODEX_ROOT/skills/requesting-code-review
superpowers|subagent-driven-development|$SUPERPOWERS_CODEX_ROOT/skills/subagent-driven-development
superpowers|systematic-debugging|$SUPERPOWERS_CODEX_ROOT/skills/systematic-debugging
superpowers|test-driven-development|$SUPERPOWERS_CODEX_ROOT/skills/test-driven-development
superpowers|using-git-worktrees|$SUPERPOWERS_CODEX_ROOT/skills/using-git-worktrees
superpowers|using-superpowers|$SUPERPOWERS_CODEX_ROOT/skills/using-superpowers
superpowers|verification-before-completion|$SUPERPOWERS_CODEX_ROOT/skills/verification-before-completion
superpowers|writing-plans|$SUPERPOWERS_CODEX_ROOT/skills/writing-plans
superpowers|writing-skills|$SUPERPOWERS_CODEX_ROOT/skills/writing-skills
context7|context7-mcp|$BASE/context7/plugins/codex/context7/skills/context7-mcp
"

  while IFS='|' read -r tool name target; do
    [ -z "$name" ] && continue
    if [ "$tool" = "superpowers" ] && superpowers_is_skipped codex; then
      continue
    fi
    link="$CODEX_SKILLS_DST/$name"
    if [ ! -d "$target" ]; then
      echo "AVISO: falta $target - se omite $name para Codex"
      continue
    fi

    ensure_skill_link codex "$tool" "Codex/$name" "$link" "$target"
  done <<EOF
$CODEX_SKILL_LINKS
EOF

  install_managed_instruction_block \
    codex \
    claude-token-efficient \
    "$CODEX_HOME/AGENTS.md" \
    "$BASE/claude-token-efficient/CLAUDE.md" \
    "$CODEX_HOME/AGENTS.override.md"
  install_managed_instruction_block \
    codex \
    claude-mem-selective-recall \
    "$CODEX_HOME/AGENTS.md" \
    "$BASE/rules/claude-mem-selective-recall.md" \
    "$CODEX_HOME/AGENTS.override.md"
fi

# --- 4. claude-mem: integraciones seleccionadas + worker ----------------
if platform_is_selected claude || platform_is_selected codex; then
  echo "==> Instalando claude-mem $CLAUDE_MEM_VERSION"
  INSTALLED_CLAUDE_MEM_VERSION="$(highest_installed_claude_mem_version)"
  if [ -n "$INSTALLED_CLAUDE_MEM_VERSION" ] \
    && semver_is_greater "$INSTALLED_CLAUDE_MEM_VERSION" "$CLAUDE_MEM_VERSION"; then
    echo "ERROR: claude-mem instalado ($INSTALLED_CLAUDE_MEM_VERSION) es mas nuevo que el pin ($CLAUDE_MEM_VERSION)." >&2
    echo "No se degrada automaticamente para proteger ~/.claude-mem/claude-mem.db; actualiza el pin con ./update.sh apply." >&2
    exit 1
  fi
  if ! command -v npx >/dev/null 2>&1; then
    echo "ERROR: npx no esta disponible; instala Node.js y vuelve a ejecutar install.sh" >&2
    exit 1
  fi
  if platform_is_selected claude; then
    (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" install --ide claude-code </dev/null)
  fi
  if platform_is_selected codex; then
    (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" install --ide codex-cli </dev/null)
  fi
  (cd "$BASE" && npx "claude-mem@$CLAUDE_MEM_VERSION" start)
fi

# --- 5. Context7 MCP por plataforma -------------------------------------
if platform_is_selected claude; then
  echo "==> Registrando Context7 para Claude (scope user)"
  if claude mcp get context7 >/dev/null 2>&1; then
    echo "OK  Context7 ya estaba registrado en Claude"
  else
    claude mcp add --transport http context7 https://mcp.context7.com/mcp -s user
  fi
fi

if platform_is_selected codex; then
  echo "==> Registrando Context7 para Codex"
  if codex mcp get context7 >/dev/null 2>&1; then
    echo "OK  Context7 ya estaba registrado en Codex"
  else
    codex mcp add context7 --url https://mcp.context7.com/mcp
  fi
fi

write_install_state

if [ -n "$INSTALL_CONFLICTS" ]; then
  echo
  echo "==> Conflictos conservados (la instalacion continuo con el resto):"
  while IFS= read -r conflict; do
    [ -n "$conflict" ] || continue
    printf '  - %s\n' "$conflict"
  done <<EOF
$INSTALL_CONFLICTS
EOF
  echo "  Usa --migrate-tool <herramienta> solo si deseas transferir su administracion."
fi

# --- 6. Resumen -----------------------------------------------------------
cat <<'EOF'

==> Instalacion terminada.
  - Los archivos de instrucciones locales se generaron desde
    PROJECT_INSTRUCTIONS.md segun las plataformas seleccionadas.
  - La ruta del repo quedo registrada para migrar symlinks si la carpeta
    se mueve y se vuelve a ejecutar install.sh.
  - claude-mem quedo instalado y su worker fue iniciado.
  - Context7 funciona sin cuenta en el tier anonimo. Una API key es opcional.
  - Inicia una sesion nueva del agente para que cargue los nuevos archivos,
    skills y hooks. Los agentes leen esas instrucciones al comenzar la sesion.

==> Nota de versiones (importante en una maquina nueva):
  - Repos 'pinned' (superpowers, prompt-master, abogado-del-diablo,
    the-architect, cyber-neo): quedan en el commit exacto fijado en third-party-repos.txt.
    Reproducibles: la maquina nueva tiene la misma version que la anterior.
  - Repos 'shallow' (context7, claude-token-efficient): traen el ULTIMO estado
    de la rama al momento de correr este script, NO una version fija. Si el
    autor upstream los cambio, aqui recibiras esa version nueva.
    Para fijarlos: en third-party-repos.txt cambia su modo a 'pinned' y pon un
    commit; luego borra su carpeta y vuelve a correr install.sh.
EOF
