#!/usr/bin/env bash
# Pruebas aisladas de la generacion de instrucciones por plataforma.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

PROJECT="$TMP/project"
mkdir -p "$PROJECT"
cp "$ROOT/install.sh" \
  "$ROOT/platforms.txt" \
  "$ROOT/PROJECT_INSTRUCTIONS.md" \
  "$PROJECT/"
chmod +x "$PROJECT/install.sh"

echo "TEST: genera archivos para varias plataformas"
"$PROJECT/install.sh" \
  --platform claude \
  --platform codex \
  --instructions-only \
  > "$TMP/first.log"

for generated in CLAUDE.md AGENTS.md; do
  [ -f "$PROJECT/$generated" ]
  grep -Fx '<!-- Generated by setup-ai-tools from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->' "$PROJECT/$generated" >/dev/null
  tail -n +3 "$PROJECT/$generated" | cmp -s - "$PROJECT/PROJECT_INSTRUCTIONS.md"
done

echo "TEST: una segunda generacion es idempotente"
before_claude="$(shasum -a 256 "$PROJECT/CLAUDE.md" | awk '{print $1}')"
before_agents="$(shasum -a 256 "$PROJECT/AGENTS.md" | awk '{print $1}')"
mkdir -p "$TMP/bin"
printf '%s\n' '#!/bin/sh' 'exit 0' > "$TMP/bin/claude"
printf '%s\n' '#!/bin/sh' 'exit 0' > "$TMP/bin/codex"
chmod +x "$TMP/bin/claude" "$TMP/bin/codex"
PATH="$TMP/bin:/usr/bin:/bin" "$PROJECT/install.sh" --instructions-only > "$TMP/second.log"
[ "$before_claude" = "$(shasum -a 256 "$PROJECT/CLAUDE.md" | awk '{print $1}')" ]
[ "$before_agents" = "$(shasum -a 256 "$PROJECT/AGENTS.md" | awk '{print $1}')" ]

echo "TEST: actualiza archivos generados con la marca anterior"
{
  printf '%s\n\n' '<!-- Generated by setup-skills from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->'
  cat "$PROJECT/PROJECT_INSTRUCTIONS.md"
} > "$PROJECT/AGENTS.md"
"$PROJECT/install.sh" --platform codex --instructions-only > "$TMP/legacy-marker.log"
grep -Fx '<!-- Generated by setup-ai-tools from PROJECT_INSTRUCTIONS.md. Do not edit directly. -->' "$PROJECT/AGENTS.md" >/dev/null

echo "TEST: conserva un archivo de instrucciones ajeno"
printf '%s\n' '# Instrucciones locales del usuario' > "$PROJECT/AGENTS.md"
if "$PROJECT/install.sh" --platform codex --instructions-only > "$TMP/foreign.log" 2>&1; then
  echo "FAIL: install.sh sobrescribiria un AGENTS.md ajeno" >&2
  exit 1
fi
grep -Fx '# Instrucciones locales del usuario' "$PROJECT/AGENTS.md" >/dev/null

echo "TEST: rechaza plataformas no registradas"
if "$PROJECT/install.sh" --platform inexistente --instructions-only > "$TMP/unknown.log" 2>&1; then
  echo "FAIL: install.sh acepto una plataforma no registrada" >&2
  exit 1
fi

echo "PASS: generacion de instrucciones por plataforma"
